### ISSUE TITLE
packages\DllExport.1.5.0\tools\net.r_eg.DllExport.targets(42,5): error : error : Failed to define security permission set for 0x20000001

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#19]

**Comment by 3F** [comment]
nice

> ... with administrator privileges

**only with** ? and what IL Assembler from your settings ? anyway, can you check with both type ? Thanks,

**Comment by OmegaExtern** [comment]
> only with ?

Well, this is new.
Can you be more specific, what's your question?

> what IL Assembler from your settings ?

I have used Direct-Mod...
I don't have time for testing this now, I've expected v1.5 to work just right, and it just disappointed me.

**Comment by 3F** [comment]
> Can you be more specific,

only when you build with administrator privileges ?

> I have used Direct-Mod...

My question about IL Assembler  ! 1.5+ now provides also my version of coreclr /ILAsm [[?](https://github.com/3F/DllExport#coreclr---ilasm--ildasm)]

Look here: https://github.com/3F/DllExport/issues/17

![ilasm](https://cloud.githubusercontent.com/assets/3246589/20076281/e6bd8bd6-a548-11e6-8fb0-d124438d969e.png)

```xml
<DllExportOurILAsm>true</DllExportOurILAsm>
```
So, what coreclr version ?

**Comment by 3F** [comment]
unfortunately I can't reproduce your problem on `v1.5.0.33792 [ ab1c3e6 ]`
*also with administrator privileges*

I need details - how to reproduce your problem ?



You can also attach the build log and project file.

But initially to set detailed or diagnostic verbosity:

For VS IDE:

* `Tools` - `Options` - `Project and Solutions` - `Build and Run` - MSBuild project build verbosity

For msbuild.exe:

`/verbosity:detailed` / `/verbosity:Diagnostic` or `/v:d` /  `/v:diag`

**Comment by 3F** [comment]
I've plan to release minor changes on this week as patch to fix - #20

Therefore, if you want to find fixes for this as soon as possible with new patch release: you have ~3-4days to describe this problem in details (how to reproduce, full build log, project file etc.)

**Comment by bidolah** [comment]
I have this error when package "Costura.Fody" https://github.com/Fody/Costura installed.

**Comment by bidolah** [comment]
Advance Build Setting -> Output ->Debug info set to none fixed this problem. But I need debug my program

**Comment by 3F** [comment]
@bidolah 

> I have this error when package "Costura.Fody" https://github.com/Fody/Costura installed.
>    Advance Build Setting -> Output ->Debug info set to "none"
>    DllExportOurILAsm = false
>    This steps fix this error. But I need debug my program

Did I understand correctly that you have `Failed to define security permission set for 0x20000001` when you are using Costura.Fody + `DllExportOurILAsm = true` ?

send me your build log with diagnostic verbosity

see also bug for Fody/ModuleInit - issue #17

**Comment by bidolah** [comment]
@3F 
Yes,
> Did I understand correctly that you have Failed to define security permission set for 0x20000001 when you are using Costura.Fody + DllExportOurILAsm = true ?
> 
**<Costura.Fody + DllExportOurILAsm = true>**  ==> **Failed to define security permission set for 0x20000001**

**<Costura.Fody + DllExportOurILAsm = false>**  ==> **error : Undeclared identifier IL_0098**

> Severity	Code	Description	Project	File	Line	Suppression State
Error		~PRIVATE~\AppData\Local\Temp\tmp261F\~PRIVATE.il(2297) : error : Undeclared identifier IL_0098
~PRIVATE\Application.cs(69) : error : syntax error at token ':' in:     IL_0098:  br.s       IL_009a	~PRIVATE~	packages\DllExport.1.5.1\tools\net.r_eg.DllExport.targets	42	
> 

**OR**(when i delete part of AppDomain.AssemblyResolve Event)

>Severity	Code	Description	Project	File	Line	Suppression State
Error		~PRIVATE.il(11601) : error : Undeclared identifier IL_0186
~PRIVATE\ServiceConfiguration.cs(130) : error : syntax error at token ':' in:     IL_0186:  br.s       IL_0188	~PRIVATE\packages\DllExport.1.5.1\tools\net.r_eg.DllExport.targets	42	

> 

 
Part  of building log ****<Costura.Fody + DllExportOurILAsm = true>**  ==> **Failed to define security permission set for 0x20000001****

> 
1>  Deleting unused reference to DllExport. (TaskId:63)
1>  Parsing 30839 lines of IL took 286 ms. (TaskId:63)
1>  calling '"~PRIVATE~"\packages\DllExport.1.5.1\tools\coreclr\ilasm.exe' with /nologo "/out:"~PRIVATE~"\" ""~PRIVATE~"\\AppData\Local\Temp\tmp5B69\"~PRIVATE~".il" /DLL  "/resource="~PRIVATE~".res"  /debug  /PE64  /X64  /CVRES="C:\Windows\Microsoft.NET\Framework\v4.0.30319/" (TaskId:63)
1>  ilasm '"~PRIVATE~"\\packages\DllExport.1.5.1\tools\coreclr\ilasm.exe' returned gracefully. (TaskId:63)
1>"~PRIVATE~"\packages\DllExport.1.5.1\tools\net.r_eg.DllExport.targets(42,5): error : error : Failed to define security permission set for 0x20000001
1>"~PRIVATE~"\packages\DllExport.1.5.1\tools\net.r_eg.DllExport.targets(42,5): error : 
1>     at RGiesecke.DllExport.Parsing.IlParser.RunIlTool(String installPath, String toolFileName, String requiredPaths, String workingDirectory, String settingsName, String arguments, String toolLoggingCode, String verboseLoggingCode, IDllExportNotifier notifier, Int32 timeout, Func`2 suppressErrorOutputLine) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Parsing\IlParser.cs:line 378
1>     at RGiesecke.DllExport.Parsing.IlAsm.RunCore(CpuPlatform cpu, String fileName, String ressourceParam, String ilSuffix) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Parsing\ILAsm.cs:line 148
1>     at RGiesecke.DllExport.Parsing.IlAsm.Run(String outputFile, String ilSuffix, CpuPlatform cpu) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Parsing\ILAsm.cs:line 118
1>     at RGiesecke.DllExport.Parsing.IlAsm.ReassembleFile(String outputFile, String ilSuffix, CpuPlatform cpu) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Parsing\ILAsm.cs:line 80
1>     at RGiesecke.DllExport.DllExportWeaver.reassembleFile(IlAsm ilAsm, String outputFile, String ilSuffix, CpuPlatform cpu) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\DllExportWeaver.cs:line 196
1>     at RGiesecke.DllExport.DllExportWeaver.RunIlAsm(IlAsm ilAsm) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\DllExportWeaver.cs:line 147
1>     at RGiesecke.DllExport.DllExportWeaver.Run() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\DllExportWeaver.cs:line 87
1>     at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 437 (TaskId:63)
1>Done executing task "DllExportAppDomainIsolatedTask" -- FAILED. (TaskId:63)
1>Done building target "DllExportMod" in project "~PRIVATE~" -- FAILED.: (TargetId:101)

**Comment by 3F** [comment]
Thanks for details !

Now it reproduced for me when I use the SecurityPermission.

```
error : Failed to define security permission set for ...
```

**0x02000004**

For this:

```csharp
[System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.Demand)]
internal class ClassA
{ }
```

your **0x20000001**

For this:

```csharp
[assembly: SecurityPermission(SecurityAction.RequestMinimum)] 
```

So, our bug from [Assembler::EmitSecurityInfo](https://github.com/3F/coreclr/blob/master/src/ilasm/assembler.cpp#L2348)

but mainly, the open ilasm on CoreCLR has a lot of restrictions :( like [this](https://github.com/3F/coreclr/issues/3), or [this](https://github.com/3F/coreclr/issues/6).
