### ISSUE TITLE
Target platform detection failure bug

### ISSUE THREAD

**Issue by OmegaExtern** [3F/DllExport#34]
I have discovered a bug in DllExport (v1.5.2), it breaks the compilation with the following error:
```
The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Unknown cpu platform 'MyCustomPlatform'.
Parameter name: platformTarget

Server stack trace: 
   at RGiesecke.DllExport.Utilities.ToCpuPlatform(String platformTarget) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Utilities.cs:line 76
   at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 414
   at RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:line 397
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	DllExport			
```

For easier reproducing of this issue, you can download VS2017 solution from here, and then try to build it:
[DllExport-Platform-issue.zip](https://github.com/3F/DllExport/files/976140/DllExport-Platform-issue.zip)

Please examine C# project file in the file attached above. You will see that `PlatformTarget` is set to `x86`, but `$(Platform)` is set to `MyCustomPlatform`.
The bug is that DllExport uses the incorrect value for detecting "target platform" value. As you can see, it obviously uses `$(Platform)` (MyCustomPlatform) instead of `PlatformTarget` (x86).
And here is the picture of that:
![image](https://cloud.githubusercontent.com/assets/6441892/25704471/da06e32a-30d9-11e7-90c7-b4ad49c29318.png)

Please fix it :)

**Comment by 3F** [comment]
It reproduces for me with original UnmanagedExports v1.2.7

the original code uses both properties `$(Platform)` & `$(PlatformTarget)`

**temporarily**, try to redefine this in your project files like:

```xml
<DllExportPlatform>$(PlatformTarget)</DllExportPlatform>
```

**Comment by OmegaExtern** [comment]
> It reproduces for me with original UnmanagedExports v1.2.7

Yes, confirmed, this issue also exists in UnmanagedExports package too.

I have tried redefining `DllExportPlatform` to `$(PlatformTarget)` in csproj file as you have said:
```
......
    <DllExportOurILAsm>false</DllExportOurILAsm>
    <DllExportPlatform>$(PlatformTarget)</DllExportPlatform>
  </PropertyGroup>
......
```

But still it fails:
```
1>------ Build started: Project: DllExport, Configuration: Debug MyCustomPlatform ------
1>  DllExport -> E:\platform-issue\DllExport\DllExport\bin\Debug\DllExport.dll
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: System.ArgumentException: Unknown cpu platform 'MyCustomPlatform'.
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: Parameter name: platformTarget
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: 
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: Server stack trace: 
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at RGiesecke.DllExport.Utilities.ToCpuPlatform(String platformTarget) in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport\Utilities.cs:line 76
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at RGiesecke.DllExport.MSBuild.ExportTaskImplementation`1.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\ExportTaskImplementation.cs:line 414
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at RGiesecke.DllExport.MSBuild.DllExportAppDomainIsolatedTask.Execute() in D:\prg\projects\DllExport\DllExport\RGiesecke.DllExport.MSBuild\RGiesecke.DllExport.MSBuild\DllExportAppDomainIsolatedTask.cs:line 397
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: 
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018: Exception rethrown at [0]: 
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at Microsoft.Build.Framework.ITask.Execute()
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>E:\platform-issue\DllExport\packages\DllExport.1.5.2\tools\net.r_eg.DllExport.targets(42,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by 3F** [comment]
probably your $(DllExportPlatform) still is empty - `Condition="'$(DllExportPlatform)' == ''"`
that is, check a correct definition of the $(PlatformTarget) (it should be after first def, because the msbuild analyzer looks this from up to down as I remember) or again, try manually: `x64`, `x86`, `Win32`, ...

**Comment by Cloudhax23** [comment]
I cannot seem to get your solutions to the issue to work. I have attempted to switch the platformtarget to x64 manually and that did not work either.

**Comment by 3F** [comment]
I'm watching that original code uses **anycpu** keyword to get value in order from: 
* `DllExportPlatform` -> `DllExportCpuType` -> `DllExportPlatformTarget`.

So you can also use this to skip processing in any places instead of x64/x86 as I said above.

```xml
<PropertyGroup>
    ...
  <!-- 
  
    just to be clear, how msbuild will consider your xml: 
    
    For this case, msbuild lexer can't resolve $(PlatformTarget) because its nodes still does not contain this definition. 
        That is, DllExportPlatform contain unevaluated value $(PlatformTarget) as is, in resolved context. 
        After, engine will process this, and the evaluated value should be is empty because of empty reference to variable for this name.
        
    But 'anycpu' is a evaluated value (engine don't requires additional step for evaluating) so you can freely use it in any places (before calling of our DllExportMod target of course :)) to skip processing from this property in order as I said above.
    
  -->  
  <DllExportPlatform>anycpu</DllExportPlatform>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|MyCustomPlatform'">
  <PlatformTarget>AnyCPU</PlatformTarget>
  ...
</PropertyGroup>
```

Well, I leave `DllExportCpuType` but the `DllExportPlatformTarget` is removed now.

Please check latest build - https://ci.appveyor.com/project/3Fs/dllexport/build/build-44/artifacts
